### PR TITLE
Added Project Sections and removed it from FAQ section

### PR DESCRIPTION
**Pull request by TakahiroFujitaSJB**
Added Project sections on the main page as well as removing the project description in the FAQ (to reduce redundancy) section on apply. 
It is not fully "polished" and will need attention

### CODE REVIEW

**Review by Niyousha99 — COMMENTED** [review]
Will review after we finish the project team description (remaining description to be provided by @Jhappy77)

**Comment by Jhappy77** [comment]
I recommend adding the title of the project in plain text when you hover over it (ex. it would say Aquavolution here)
image

**Comment by Jhappy77** [comment]
For homepage project description:
```
Every year, Tech Start runs a handful of year-long software development projects, each led by an experienced project manager. Each project aims to solve a compelling problem by harnessing technology and entrepreneurial principles. Our members participate in every stage of the software development lifecycle, and each team involves a diversity of roles like software developers, business strategists, and designers. At the end of the year, teams present their finished projects to our sponsors at our annual showcase, and members can add their project to their portfolio to supercharge their career prospects. Joining a Tech Start project is the best way to gain skills, meet friends, and network with the tech community on campus.
```

For Projects Q&A:

```
Q: Do we try to monetize projects?
Tech Start projects are themed around startups and entrepreneurship. Our teams use entrepreneurial thinking to guide their decision making and design their project around fulfilling a specific market niche and meeting the needs of a target audience. Despite this theme, Tech Start projects are _not_ about building real startups - instead, we're focused on teaching skills, providing mentorship, and building projects that can boost your portfolio and your career. That said, if you want to pursue your project as a real entrepreneurial venture and monetize it outside of Tech Start, we're able to provide support and direct you to resources that you can use.```

**Comment by Jhappy77** [comment]
Also @TakahiroFujitaSJB I recommend making a separate branch for every pull request. When you complete the PR, you can delete the branch, and make a new branch for the next pr you work on

**Comment by Niyousha99** [comment]
> I recommend adding the title of the project in plain text when you hover over it (ex. it would say Aquavolution here) image

Thanks for the feedback! We will address this as part of a separate issue :)

**Review by Niyousha99 — APPROVED** [review]
Everything looks good now!

**Review by Sahitiakella — APPROVED** [review]
Looks great :)

**Pull request merged**
