### PR TITLE
Updated Exec Photo

### PR DESCRIPTION
**Pull request by Sahitiakella**

### CODE REVIEW

**Comment by kamadorueda** [comment]
@Sahitiakella Please rebase the `dev` branch, that way it would be easier to review the changes made by you. Your PR has a few old commits that would go away by rebasing

**Review by kamadorueda — APPROVED** [review]
We just rebased the branch, so I assume the extra commits are a GitHub UI bug, the real change is just: https://github.com/Tech-Start-UCalgary/tsu-website/pull/361/commits/46fbc87ed07bad539f02a5e36e07511fb4737ca5

As proven by https://github.com/Tech-Start-UCalgary/tsu-website/compare/dev...UpdateExecPhoto

Changes look good to me

**Comment by kamadorueda** [comment]
@Niyousha99 I think 2 approvals are required before merging, so I cannot merge this until someone else approves

**Review by Niyousha99 — APPROVED** [review]
LGTM

**Pull request merged**
